version: "3.8"

services:
  api:
    container_name: evolution_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - evolution_instances:/evolution/instances
      - evolution_data:/evolution/prisma/data
    networks:
      - evolution-net
    env_file:
      - .env
    expose:
      - "8080"

  frontend:
    container_name: evolution_frontend
    image: evoapicloud/evolution-manager:latest
    restart: always
    ports:
      - "3000:80"
    networks:
      - evolution-net

volumes:
  evolution_instances:
  evolution_data:

networks:
  evolution-net:
    name: evolution-net
    driver: bridge
